services:
  react:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    container_name: ticket_react
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    networks:
      - ticket-network
    depends_on:
      - laravel

  laravel:
    build: 
      context: ./src/backend
      dockerfile: ../../docker/laravel/Dockerfile
    container_name: ticket_laravel
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/var/www/html
      - ./docker/laravel/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ticket-network
    depends_on:
      - mysql

  mysql:
    build: ./docker/mysql
    container_name: ticket_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ticket-network

  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    container_name: ticket_soketi
    restart: unless-stopped
    environment:
      SOKETI_DEBUG: ${SOKETI_DEBUG}
      SOKETI_METRICS_SERVER_PORT: ${SOKETI_METRICS_SERVER_PORT}
      SOKETI_DEFAULT_APP_ID: ${SOKETI_DEFAULT_APP_ID}
      SOKETI_DEFAULT_KEY: ${SOKETI_DEFAULT_KEY}
      SOKETI_DEFAULT_SECRET: ${SOKETI_DEFAULT_SECRET}
      SOKETI_DEFAULT_CAPACITY: ${SOKETI_DEFAULT_CAPACITY}
      SOKETI_DEFAULT_ENABLE_CLIENT_MESSAGES: ${SOKETI_DEFAULT_ENABLE_CLIENT_MESSAGES}
      SOKETI_DEFAULT_ENABLE_USER_AUTHENTICATION: ${SOKETI_DEFAULT_ENABLE_USER_AUTHENTICATION}
   
    ports:
      - "6001:6001"
    networks:
      - ticket-network

networks:
  ticket-network:
    driver: bridge

volumes:
  mysql_data:
