#!/usr/bin/env sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SOKETI_BIN="$ROOT_DIR/.runtime/soketi/node_modules/.bin/soketi"
ENV_FILE="$ROOT_DIR/.env"

env_value() {
    key=$1
    if [ ! -f "$ENV_FILE" ]; then
        return 0
    fi
    grep -E "^${key}=" "$ENV_FILE" | tail -n 1 | cut -d= -f2- | sed 's/^"//; s/"$//; s/^'\''//; s/'\''$//'
}

if [ ! -x "$SOKETI_BIN" ]; then
    echo "Soketi is not installed. Run ./setup-production.sh first." >&2
    exit 1
fi

export SOKETI_DEBUG="${SOKETI_DEBUG:-$(env_value SOKETI_DEBUG)}"
export SOKETI_HOST="${SOKETI_HOST:-$(env_value SOKETI_HOST)}"
export SOKETI_PORT="${SOKETI_PORT:-$(env_value SOKETI_PORT)}"
export SOKETI_METRICS_SERVER_PORT="${SOKETI_METRICS_SERVER_PORT:-$(env_value SOKETI_METRICS_SERVER_PORT)}"
export SOKETI_DEFAULT_APP_ID="${SOKETI_DEFAULT_APP_ID:-$(env_value SOKETI_DEFAULT_APP_ID)}"
export SOKETI_DEFAULT_KEY="${SOKETI_DEFAULT_KEY:-$(env_value SOKETI_DEFAULT_KEY)}"
export SOKETI_DEFAULT_SECRET="${SOKETI_DEFAULT_SECRET:-$(env_value SOKETI_DEFAULT_SECRET)}"
export SOKETI_DEFAULT_CAPACITY="${SOKETI_DEFAULT_CAPACITY:-$(env_value SOKETI_DEFAULT_CAPACITY)}"
export SOKETI_DEFAULT_ENABLE_CLIENT_MESSAGES="${SOKETI_DEFAULT_ENABLE_CLIENT_MESSAGES:-$(env_value SOKETI_DEFAULT_ENABLE_CLIENT_MESSAGES)}"
export SOKETI_DEFAULT_ENABLE_USER_AUTHENTICATION="${SOKETI_DEFAULT_ENABLE_USER_AUTHENTICATION:-$(env_value SOKETI_DEFAULT_ENABLE_USER_AUTHENTICATION)}"

export SOKETI_DEBUG="${SOKETI_DEBUG:-0}"
export SOKETI_HOST="${SOKETI_HOST:-0.0.0.0}"
export SOKETI_PORT="${SOKETI_PORT:-6001}"
export SOKETI_METRICS_SERVER_PORT="${SOKETI_METRICS_SERVER_PORT:-9601}"
export SOKETI_DEFAULT_APP_ID="${SOKETI_DEFAULT_APP_ID:-app-id}"
export SOKETI_DEFAULT_KEY="${SOKETI_DEFAULT_KEY:-app-key}"
export SOKETI_DEFAULT_SECRET="${SOKETI_DEFAULT_SECRET:-app-secret}"
export SOKETI_DEFAULT_CAPACITY="${SOKETI_DEFAULT_CAPACITY:-100}"
export SOKETI_DEFAULT_ENABLE_CLIENT_MESSAGES="${SOKETI_DEFAULT_ENABLE_CLIENT_MESSAGES:-true}"
export SOKETI_DEFAULT_ENABLE_USER_AUTHENTICATION="${SOKETI_DEFAULT_ENABLE_USER_AUTHENTICATION:-true}"

exec "$SOKETI_BIN" start
